### ISSUE TITLE
add contracted sentences on playwright and cypress

### ISSUE THREAD

**Issue by stanlee974** [Orange-OpenSource/uuv#665] opened 2024-06-28 12:30 UTC
add contracted sentences to clarify usage : 
`je clique sur l'élément avec le rôle "link" et le nom "Name"` => `je clique sur le lien nommé "Name"`
`I click on element with role "link" and name "Name"` => `I click on link named "Name"`

**Comment by luifr10** [comment] 2024-08-18 15:03
Duplicate of #731

**Closed by luifr10** 2024-08-18 15:03 UTC
Labels: enhancement, good first issue
